### ISSUE TITLE
Exception on cubeId on DF with single row

### ISSUE THREAD

**Issue by polsm91** [Qbeast-io/qbeast-spark#128]
## What went wrong?

Indexing a DataFrame on a column of type Int and with a single row throws an exception. It seems related to how we estimate the space with Integers, since I can't reproduce the bug with Strings.

### 1. Code that triggered the bug, or steps to reproduce:

```scala
// This fails
List(95).toDF.write.format("qbeast").option("columnsToIndex","value").save("/tmp/debug-assert")
// While this works
List("95").toDF.write.format("qbeast").option("columnsToIndex","value").save("/tmp/debug-assert2")
```

### 2. Branch and commit id:
Pull request: https://github.com/Qbeast-io/qbeast-spark/pull/124
Branch: `42-table-writes-catalog`
Commit id: 8894e91a94e6e595cd702d9d5194f094713d91ee

### 3. Spark version:
3.1.3

### 4. Hadoop version:
3.2.0

### 5. How are you running Spark?
Local

### 6. Stack trace:

```java
java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:268)
        at io.qbeast.core.model.CubeId$.containers(CubeId.scala:66)
        at io.qbeast.core.model.CubeWeightsBuilder.resultInternal(CubeWeights.scala:101)
        at io.qbeast.core.model.CubeWeightsBuilder.result(CubeWeights.scala:92)
        at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.$anonfun$estimatePartitionCubeWeights$4(OTreeDataAnalyzer.scala:161)
        at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:195)

```

**Comment by Adricu8** [comment]
The same error happens when you index a DF with multiple rows of the same value.

**Comment by osopardo1** [comment]
As @Adricu8 pointed out, there's a bug in `IdentityTransformation` (when a column indexed has a unique value). This value is mapped as `value.byteValue()`, that can give you a Double up to 2^8. An easy solution is to map all values for that transformation to 0.0 (as we do for nulls).
