### ISSUE TITLE
Writing to S3 using the Quickstart setup fails with NoSuchMethodError

### ISSUE THREAD

**Issue by polsm91** [Qbeast-io/qbeast-spark#22]
**What went wrong?**

After following the [Quickstart](https://github.com/Qbeast-io/qbeast-spark/blob/main/docs/Quickstart.md) I tried writing a dataset into S3 and failed. I tracked down the issue to the Hadoop version. 

Spark 3.1.x is shipped with Hadoop 3.2.0 ([See here](
https://github.com/apache/spark/blob/de351e30a90dd988b133b3d00fa6218bfcaba8b8/pom.xml#L123)) while the qbeast-spark quickstart recommends Hadoop 3.2.2 dependencies. 

**How to reproduce?**
1. Code that triggered the bug, or steps to reproduce:

```scala
val df = spark.read.format("csv").option("header","true").option("inferSchema", "true")
.load("./src/test/resources/ecommerce300k_2019_Nov.csv")

df.write.format("qbeast").option("columnsToIndex","product_id,price").save("s3a://my_bucket/qbeast-ecommerce")
```

2. Branch and commit id:
Commit 4f37b584065f99b48e848eeaaa6304bc92223feb on branch Main

3. Spark version:
3.1.2

4. Hadoop version:
3.2.0

5. Are you running Spark inside a container? Are you launching the app on a remote K8s cluster? Or are you just running the tests in a local computer?
Local computer writing to remote S3

6. Stack trace:
```scala
java.lang.NoSuchMethodError: 'void org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(java.util.concurrent.ExecutorService, int, boolean)'
	at org.apache.hadoop.fs.s3a.S3AFileSystem.create(S3AFileSystem.java:824)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
	at org.apache.parquet.hadoop.util.HadoopOutputFile.create(HadoopOutputFile.java:74)
	at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:248)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:390)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:349)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetOutputWriter.<init>(ParquetOutputWriter.scala:36)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anon$1.newInstance(ParquetFileFormat.scala:149)
	at io.qbeast.spark.sql.qbeast.BlockWriter.buildWriter(BlockWriter.scala:135)
	at io.qbeast.spark.sql.qbeast.BlockWriter.$anonfun$writeRow$3(BlockWriter.scala:73)
	at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:104)
	at io.qbeast.spark.sql.qbeast.BlockWriter.$anonfun$writeRow$1(BlockWriter.scala:73)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:162)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
	at io.qbeast.spark.sql.qbeast.BlockWriter.writeRow(BlockWriter.scala:64)
	at io.qbeast.spark.sql.qbeast.QbeastWriter.$anonfun$writeFiles$1(QbeastWriter.scala:172)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by eavilaes** [comment]
I couldn't manage to make Hadoop 3.2 work with Azure Blob Storage. I think it would be great to have a table of recommended/stable versions per cloud provider, if possible.
