### ISSUE TITLE
BIGINT type columns can't be indexed with another value than 1

### ISSUE THREAD

**Issue by cdelfosse** [Qbeast-io/qbeast-spark#409]
## What went wrong?

If a Qbeast table is created with an index on a column using the BIGINT type, it's impossible to insert values different than 1 into this column.

## How to reproduce?

Start a spark sql shell:

```shell
 $SPARK_HOME/bin/spark-sql \
--packages io.qbeast:qbeast-spark_2.12:0.7.0,io.delta:delta-spark_2.12:3.1.0 \
--conf spark.sql.extensions=io.qbeast.spark.internal.QbeastSparkSessionExtension \
--conf spark.sql.catalog.spark_catalog=io.qbeast.spark.internal.sources.catalog.QbeastCatalog
```
```sql
CREATE TABLE t (value BIGINT) USING qbeast OPTIONS ('columnsToIndex' = 'value') LOCATION '/tmp/t';
spark-sql (default)> insert into t values(1);
Time taken: 1.35 seconds
spark-sql (default)> insert into t values(2);
...
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2844)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2780)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2779)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2779)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1242)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1242)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1242)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3048)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2982)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2971)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
Caused by: scala.MatchError: 2 (of class java.lang.Long)
	at io.qbeast.core.transform.IdentityToZeroTransformation.transform(Transformation.scala:74)
	at io.qbeast.spark.index.RowUtils$.$anonfun$rowValuesToPoint$1(RowUtils.scala:47)
	at io.qbeast.spark.index.RowUtils$.$anonfun$rowValuesToPoint$1$adapted(RowUtils.scala:45)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at io.qbeast.spark.index.RowUtils$.rowValuesToPoint(RowUtils.scala:45)
	at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.$anonfun$computePartitionCubeDomains$7(OTreeDataAnalyzer.scala:169)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.$anonfun$computePartitionCubeDomains$6(OTreeDataAnalyzer.scala:168)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:198)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:890)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:890)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

You can try any values other than 1 it will fail.

### 5. How are you running Spark?

Local computer on Mac OS

**Comment by osopardo1** [comment]
I have been testing it locally with different types (aside from BIGINT), and the same error appears when executing the second command.

It seems to be more related to the fact that we are inserting one value at each time. More specifically, to the implementation of IdentityToZeroTransformation:

```scala
case class IdentityToZeroTransformation(identityValue: Any) extends Transformation {

  @inline
  override def transform(value: Any): Double = value match {

    case v: Number if v == identityValue => 0.0
    case v: Timestamp if v == identityValue => 0.0
    case v: Date if v == identityValue => 0.0
    case v: Instant if v == identityValue => 0.0

  }

  override def isSupersededBy(newTransformation: Transformation): Boolean = false

  override def merge(other: Transformation): Transformation = this

}
```

In which, if another `IdentityToZeroTransformation` is appended, it will not be merged or superseded.

**Comment by osopardo1** [comment]
Aaaaah, I see this is related to issue #224 

Are you ok if we close this one and open another one for date and bigint types?

**Comment by cdelfosse** [comment]
> Aaaaah, I see this is exactly the behaviour exposed on issue #224
> 
> Are you ok if we close this one and open another one for date and bigint types?

Sure!

**Comment by osopardo1** [comment]
Closing it because it's duplicated in #224
