### ISSUE TITLE
Error when indexing a table with BIGINT 

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#414]
## What went wrong?
When creating a table using BIGINT on a date column and inserting a set of 10 rows, a `ScalaMatch` error appears. 

We would need to investigate the flow for the BIGINT type. Is weird, because when using CREATE TABLE(id LONG) it maps the type to BIGINT in the SHOW CREATE TABLE statement. But the indexing works ok 🤔 

## How to reproduce?

Different steps about how to reproduce the problem.

### 1. Code that triggered the bug, or steps to reproduce:

```scala
spark.sql("CREATE TABLE table(date BIGINT) USING qbeast OPTIONS('columnsToIndex'='date')")
spark.sql("INSERT INTO table SELECT temp_date FROM temp_view")
```

### 2. Branch and commit id:

main 

### 3. Spark version:
On the spark shell run `spark.version`.

3.5.0

### 4. Hadoop version:
On the spark shell run `org.apache.hadoop.util.VersionInfo.getVersion()`.

3.3.4

### 5. How are you running Spark?
Are you running Spark inside a container? Are you launching the app on a remote K8s cluster? Or are you just running the tests in a local computer?

Local 
### 6. Stack trace:
Trace of the log/error messages.

```shell

java.lang.illegalargumentexception: requirement failed
        at scala.Predef$.require(Predef.scala:268)
        at io.qbeast.core.model.CubeId$.containers(CubeId.scala:88)
        at io.qbeast.core.model.CubeDomainsBuilder.computeWeightsAndSizes(CubeDomainsBuilder.scala:132)
        at io.qbeast.core.model.CubeDomainsBuilder.resultInternal(CubeDomainsBuilder.scala:118)
        at io.qbeast.core.model.CubeDomainsBuilder.result(CubeDomainsBuilder.scala:114)
        at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.$anonfun$computePartitionCubeDomains$6(OTreeDataAnalyzer.scala:177)
        at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:198)

```

**Comment by osopardo1** [comment]
I am not able to reproduce the error using a synthetic dataset in main. 

I either need:
- The original data that was written.
- Test with previous version (0.7.0). Will try this before asking for the data.

**Comment by osopardo1** [comment]
Cannot reproduce with version 0.7.0 :/
Will try with a subset of the original data.

**Comment by fpj** [comment]
@cdelfosse needs to provide a way to reproduce.

**Comment by cdelfosse** [comment]
I can reproduce this bug in the qbeast demo data studio (https://qbeast-demo.cloud.qbeast.io/), but not locally:

```
$ spark-sql
> use qbeast_demo;

> CREATE TABLE test (
    date BIGINT
)
USING qbeast
OPTIONS (columnsToIndex "date", cubeSize "100000")
LOCATION 's3://qbeast-demo/test/';

-- Transform the date which is a string as a bigint, and insert into test
> INSERT INTO TABLE test SELECT CAST((unix_timestamp(to_timestamp(date, "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")) * 1000 + SUBSTRING(date, 21, 3)) AS BIGINT) AS timestamp_bigint FROM datadog_logs_qbeast limit 10;

24/10/31 09:02:52 WARN TaskSetManager: Lost task 0.0 in stage 48.0 (TID 8514) (192.168.117.62 executor 1): java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:268)
        at io.qbeast.core.model.CubeId$.containers(CubeId.scala:88)
        at io.qbeast.core.model.CubeDomainsBuilder.computeWeightsAndSizes(CubeDomainsBuilder.scala:132)
        at io.qbeast.core.model.CubeDomainsBuilder.resultInternal(CubeDomainsBuilder.scala:118)
        at io.qbeast.core.model.CubeDomainsBuilder.result(CubeDomainsBuilder.scala:114)
        at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.$anonfun$computePartitionCubeDomains$6(OTreeDataAnalyzer.scala:177)
        at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:198)
...
```

**Comment by cdelfosse** [comment]
I made a video of how to reproduce the bug: https://drive.google.com/file/d/1G9bUKJqV-b6O8IykHl6tFwzvNk1cGU3Z/view

Here is the backtrace at the end:
```
24/11/04 11:34:48 WARN TaskSetManager: Lost task 0.0 in stage 54.0 (TID 11322) (192.168.126.12 executor 1): org.apache.spark.SparkException: [FAILED_EXECUTE_UDF] Failed to execute user defined function (`SparkPointWeightIndexer$$Lambda$5782/0x00007f2b45836d18`: (struct<date:bigint>, int) => array<binary>).
        at org.apache.spark.sql.errors.QueryExecutionErrors$.failedExecuteUserDefinedFunctionError(QueryExecutionErrors.scala:198)
        at org.apache.spark.sql.errors.QueryExecutionErrors.failedExecuteUserDefinedFunctionError(QueryExecutionErrors.scala)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.generate_doConsume_0$(Unknown Source)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
        at org.apache.spark.scheduler.Task.run(Task.scala:141)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
        at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:268)
        at io.qbeast.core.model.CubeId$.containers(CubeId.scala:88)
        at io.qbeast.core.model.PointWeightIndexer.findTargetCubeIds(PointWeightIndexer.scala:44)
        at io.qbeast.spark.index.SparkPointWeightIndexer.$anonfun$findTargetCubeIdsUDF$1(SparkPointWeightIndexer.scala:38)
        at io.qbeast.spark.index.SparkPointWeightIndexer.$anonfun$findTargetCubeIdsUDF$1$adapted(SparkPointWeightIndexer.scala:35)
        ... 19 more
```

**Comment by osopardo1** [comment]
Okei, this issue seems to be turning out far more complex than we initially thought. I'm still trying to reproduce the behavior locally with a small amount of data, but here are my findings: 

- For context: when indexing a DataFrame, we load it twice. One for analyzing the min/max and count values of the columns, and other to actually index each row. 
- I've experienced the same error with different configurations of `maxNumberOfExecutors`. But using just 1 give no problems.
- Using the LIMIT clause gives non-deterministic results when analyzing and indexing the DataFrame. This makes the initial min/max of the DataFrame different that the final inserted data. And we need the min/max for normalizing the values to the [0.0, 1.0) space. That is why CubeId fails: it detects a value outside this range and does not know how to create the particular cube. 
- Appending new data to the source table while indexing can give the same inconsistency, because min/max is affected after being computed. Example:
    - Insert Data (1, 2, 3)
    - Analyze (1, 2, 3) = min:1, max:3
    - Insert Data (4, 5, 6)
    - Finish inserting (4, 5, 6)
    - Index (1, 2, 3, 4, 5, 6) -> (4, 5, 6) falls out of min:1, max:3 -> error
- This behavior is not experienced in smaller scales, because the time window between Analyzing the data frame and Indexing is not big enough. But if we are talking about large amounts of data, I think it can cause inconsistencies. 


A solution:
- Use `columnStats` to hardcode the Revision parameters. If we are indexing timestamps, we can create a Revision that goes from the first date + one year forward. 
```
CREATE TABLE test (date BIGINT) 
USING qbeast 
OPTIONS (
    columnsToIndex = "date",
    cubeSize = "100000",
    columnStats = "{\"date_min\": 1720766770250, \"date_max\": 1730905198741}"
);
```

**Comment by osopardo1** [comment]
I've tested the solution proposed (`columnStats`), and the error does not show anymore. It fails due to a task killed when arriving at the DataWriter stage, but that is another issue. 

Another worrying problem might be the usage of `dynamicAllocation`.

As far as I understand, `dynamicAllocation` asks for resources if needed. Are we sure that these resources have access to the cached data (which I don't think so)? If that is the case, it can be possible to face inconsistencies when doing the double pass through the DataFrame. That would explain why experiments with a single core are deterministic.

**Comment by osopardo1** [comment]
What I am sure right now is that this issue should be close, and I would open another one with a better explanation.

**Comment by osopardo1** [comment]
The error can be reproduced locally with this code:

```scala
    // Define the test data
    val df1 = spark.range(1, 10000).toDF("id") // bigger append

    // Specify the path where data will be written
    // val tmpWarehouse = "/tmp/qbeast_concurrency_test"
    val destinationTable = "append_test_table_destination"
    val sourceTable = "append_test_table_source"
    val destinationPath = s"$tmpWarehouse/$destinationTable"
    val sourcePath = s"$tmpWarehouse/$sourceTable"

    spark.sql(s"""CREATE TABLE $sourceTable (id LONG)
         | USING qbeast LOCATION '$sourcePath'
         | OPTIONS (columnsToIndex 'id', cubeSize '100')""".stripMargin)
    spark.sql(s"""CREATE TABLE $destinationTable (id LONG)
         | USING qbeast LOCATION '$destinationPath'
         | OPTIONS (columnsToIndex 'id', cubeSize '100')""".stripMargin)

    // Define the append function
    def appendDataSource(df: org.apache.spark.sql.DataFrame): Unit = {
      df.write.format("qbeast").mode("append").save(sourcePath)
    }

    def appendDataDestinationQbeast(): Unit = {
      spark.sql(s"INSERT INTO $destinationTable SELECT id FROM $sourceTable")
    }

    // First append
    appendDataSource(df1)

    // Define thread for append1
    val thread1 = new Thread(new Runnable {
      def run(): Unit = {
        try {
          println("Starting append in DESTINATION...")
          appendDataDestinationQbeast() // Perform append2
          println("append in DESTINATION completed.")
        } catch {
          case e: Exception =>
            println(s"Error: $e")
        }
      }
    })

    // Define thread for append2

    val thread2 = new Thread(new Runnable {
      def run(): Unit = {
        println("Starting append in SOURCE...")
        val numberOfSmallAppends = 10
        var count = 0
        var lastRange = 100000
        while (count < numberOfSmallAppends) {
          println(s"Appending $count")
          val df = spark.range(lastRange, lastRange + 10).toDF("id")
          try {
            appendDataSource(df) // Perform append1
            count += 1
            lastRange += 10
            println(s"Appended $count finished")
          } catch {
            case e: Exception =>
              println(s"Error: $e")
              return
          }
        }
        println("append in SOURCE completed")
      }
    })

    // Start both threads
    thread1.start()
    thread2.start()

    // Wait for both threads to complete
    thread1.join()
    thread2.join()

    // Verify the results
    val resultSourceDF = spark.read.format("qbeast").load(sourcePath)
    val resultDestinationDF = spark.read.format("qbeast").load(destinationPath)

    // Check row count to verify both DataFrames were appended
    val expectedRowCount = resultSourceDF.count()
    val actualRowCount = resultDestinationDF.count()

    assert(
      actualRowCount == expectedRowCount,
      s"Test failed! Expected $expectedRowCount rows but found $actualRowCount.")
```
